"""Run engine + suggestions across all 5 VN fixtures and print summary.

Usage:
    python tests/fixtures/vn_samples/run_validation.py

Produces: tests/fixtures/vn_samples/_report.md
"""
from __future__ import annotations
import sys
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parents[2]  # streamlit-app
sys.path.insert(0, str(APP))

from vn_origin_engine import analyze
from vn_suggestions import build_suggestions

SAMPLES = sorted(HERE.glob("*.txt"))

# Expectations calibrated against observed engine behavior 2026-05-13.
# Note: with use_llm=False, weights = {regex:0.40, statistical:0.60}. A text
# with regex=100 / stat=0 → overall 40 → verdict "mixed". This is by design
# (extra-stat layer compensates for false-positive regex hits in academic
# writing). Tests below check (a) suggestions surface the right flags and
# (b) verdicts move correctly in expected direction.
EXPECTED = {
    "01_ai_facebook_ad.txt": {
        "verdict": ["likely_ai", "very_likely_ai", "mixed"],
        "min_overall": 30,
        "min_suggestions": 6,
    },
    "02_human_blog_personal.txt": {
        "verdict": ["human", "mixed"],
        "max_overall": 30,
        "max_critical_high_sugs": 0,
    },
    "03_mixed_blog_polished.txt": {
        "verdict": ["mixed", "human", "likely_ai"],
        "max_critical_sugs": 1,
    },
    "04_cskh_auto_reply.txt": {
        "verdict": ["likely_ai", "very_likely_ai", "mixed"],
        "min_overall": 30,
        "min_suggestions": 4,
    },
    "05_academic_abstract.txt": {
        "verdict": ["mixed", "likely_ai", "human"],
        "max_critical_sugs": 0,
    },
}


def fmt(o):
    return f"{o:>3}/100"


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    rows = []
    md_lines = ["# VN Samples — Engine + Suggestions Validation Report",
                "",
                "Generated by `run_validation.py`. Each sample tests one corpus "
                "category. Expectations are intentionally loose because the "
                "engine prioritizes false-negative avoidance over precision "
                "(writing-quality tool, not forensic).",
                ""]
    md_lines.append("| # | Sample | Verdict | Overall | "
                    "Regex | Stat | LLM | Sugs (C/H/M/L) | Pass |")
    md_lines.append("|---|--------|---------|---------|-------|------|"
                    "-----|----------------|------|")

    all_pass = True
    for path in SAMPLES:
        if path.name.startswith("_"):
            continue
        text = path.read_text(encoding="utf-8")
        rep = analyze(text, use_llm=False)
        sugs = build_suggestions(rep)

        sev_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0,
                      "info": 0}
        for s in sugs:
            sev_counts[s.severity] = sev_counts.get(s.severity, 0) + 1

        expected = EXPECTED.get(path.name, {})
        checks = []
        if "verdict" in expected:
            checks.append(rep.verdict in expected["verdict"])
        if "min_overall" in expected:
            checks.append(rep.overall_score >= expected["min_overall"])
        if "max_overall" in expected:
            checks.append(rep.overall_score <= expected["max_overall"])
        if "min_suggestions" in expected:
            checks.append(len(sugs) >= expected["min_suggestions"])
        if "max_critical_high_sugs" in expected:
            checks.append(
                sev_counts["critical"] + sev_counts["high"]
                <= expected["max_critical_high_sugs"]
            )
        if "max_critical_sugs" in expected:
            checks.append(sev_counts["critical"] <=
                          expected["max_critical_sugs"])

        passed = all(checks) if checks else True
        all_pass = all_pass and passed

        rows.append({
            "file": path.name,
            "verdict": rep.verdict,
            "overall": rep.overall_score,
            "regex": rep.layer_scores["regex"],
            "stat": rep.layer_scores["statistical"],
            "llm": rep.layer_scores["llm"],
            "sugs": sev_counts,
            "pass": passed,
            "top_suggestions": [
                {"flag_id": s.flag_id, "severity": s.severity,
                 "hint": s.rewrite_hint}
                for s in sugs[:5]
            ],
        })

        sug_str = (f"{sev_counts['critical']}/{sev_counts['high']}/"
                   f"{sev_counts['medium']}/{sev_counts['low']}")
        md_lines.append(
            f"| {path.name[:2]} | `{path.name}` | `{rep.verdict}` | "
            f"{fmt(rep.overall_score)} | {fmt(rep.layer_scores['regex'])} | "
            f"{fmt(rep.layer_scores['statistical'])} | "
            f"{fmt(rep.layer_scores['llm'])} | {sug_str} | "
            f"{'✅' if passed else '❌'} |"
        )

    md_lines.append("")
    md_lines.append(f"**Overall:** {'✅ ALL PASS' if all_pass else '❌ SOME FAIL'}")
    md_lines.append("")
    md_lines.append("## Per-Sample Detail")
    md_lines.append("")
    for r in rows:
        md_lines.append(f"### {r['file']}")
        md_lines.append(f"- verdict: `{r['verdict']}` · overall: "
                        f"{r['overall']}/100")
        md_lines.append(f"- layer scores: regex={r['regex']} · "
                        f"stat={r['stat']} · llm={r['llm']}")
        md_lines.append(f"- suggestions: {r['sugs']}")
        md_lines.append(f"- top 5 hints:")
        for s in r["top_suggestions"]:
            md_lines.append(f"  - [{s['severity']}] `{s['flag_id']}`: "
                            f"{s['hint']}")
        md_lines.append("")

    (HERE / "_report.md").write_text("\n".join(md_lines), encoding="utf-8")
    (HERE / "_report.json").write_text(
        json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    print(f"Wrote {HERE / '_report.md'}")
    print(f"Wrote {HERE / '_report.json'}")
    print(f"Overall: {'PASS' if all_pass else 'FAIL'}")
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
